# This is a basic workflow to help you get started with Actions

name: Run_py-lexer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lexertest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install diffutils
        run: sudo apt-get update && sudo apt-get install -y diffutils 
        # Install diffutils package which includes the diff command
        
      # Runs a set of commands using the runners shell
      - name: Compare differences in outputs
      # iterate through files
      # run python lexer on committed file
      # compare committedoutput.txt to the file's output
      # output the differences
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          committedList=' ' read -ra file_array <<< "$files"
                    
          for file in "${file_array[@]}"; do
            file_extension="${file##*.}"
            echo "Committed file: $file, Extension: $file_extension"
            cat $file.$file_extension
            python3 py.lex > committed_output.txt
            
            gcc $file.$file_extension
            ./a.out > expected_output.txt
            
            diff committed_output.txt expected_output.txt > output_diff.txt || true
            if [ -s output_diff.txt ]; then
              echo "Outputs are different"
              cat output_diff.txt
              exit 1
            else
              echo "Outputs are identical"
            fi
          done
